# Generated by Django 5.2.3 on 2025-07-01 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default='Mcc@123', max_length=128)),
                ('password_changed', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('department', models.CharField(max_length=1000)),
                ('department_order', models.IntegerField()),
                ('institution', models.CharField(default='Madras Christian College', max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('website', models.URLField(max_length=1000, null=True)),
                ('profile_picture', models.ImageField(upload_to='profile_pics/')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Details', to='UserDetails.user')),
            ],
        ),
        migrations.CreateModel(
            name='Resource_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_topic', models.CharField(max_length=1000)),
                ('resource_department', models.CharField(max_length=1000)),
                ('resource_date', models.CharField(max_length=1000)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Resource_Person', to='UserDetails.user')),
            ],
        ),
        migrations.CreateModel(
            name='Research_ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_title', models.CharField(max_length=1000)),
                ('research_link', models.URLField(max_length=1000, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Research_ID', to='UserDetails.user')),
            ],
        ),
        migrations.CreateModel(
            name='Research_Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_career_details', models.CharField(max_length=1000)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Research_Career', to='UserDetails.user')),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_areas', models.CharField(max_length=1000)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Research', to='UserDetails.user')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_title', models.CharField(max_length=1000)),
                ('publication_link', models.URLField(max_length=1000)),
                ('publication_type', models.CharField(max_length=1000)),
                ('publication_month_and_year', models.CharField(max_length=1000)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Publication', to='UserDetails.user')),
            ],
        ),
        migrations.CreateModel(
            name='Phd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phd_scholars_produced', models.CharField(max_length=1000)),
                ('phd_scholars_registered', models.CharField(max_length=1000)),
                ('phd_name', models.CharField(max_length=1000)),
                ('phd_topic', models.CharField(max_length=1000)),
                ('phd_status', models.CharField(max_length=1000)),
                ('phd_years_of_completion', models.CharField(max_length=1000)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Phd', to='UserDetails.user')),
            ],
        ),
        migrations.CreateModel(
            name='Honary_Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honary_position', models.CharField(max_length=1000)),
                ('honary_year', models.CharField(max_length=1000)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Honary_Position', to='UserDetails.user')),
            ],
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=1000)),
                ('funding_agency', models.CharField(max_length=1000)),
                ('funding_month_and_year', models.CharField(max_length=1000)),
                ('funding_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('funding_status', models.CharField(max_length=1000)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Funding', to='UserDetails.user')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=1000)),
                ('college', models.CharField(max_length=1000)),
                ('start_year', models.CharField(max_length=1000)),
                ('end_year', models.CharField(max_length=1000)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Education', to='UserDetails.user')),
            ],
        ),
        migrations.CreateModel(
            name='Consultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultancy_details', models.CharField(max_length=1000)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Consultancy', to='UserDetails.user')),
            ],
        ),
        migrations.CreateModel(
            name='Conferenece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_title', models.CharField(max_length=1000)),
                ('conference_details', models.CharField(max_length=1000)),
                ('conference_type', models.CharField(max_length=1000)),
                ('conference_isbn', models.CharField(max_length=1000)),
                ('conference_year', models.CharField(max_length=1000)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Conferenece', to='UserDetails.user')),
            ],
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaboration_details', models.CharField(max_length=1000)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Collaboration', to='UserDetails.user')),
            ],
        ),
        migrations.CreateModel(
            name='Career_Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_highlight_details', models.CharField(max_length=1000)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Career_Highlight', to='UserDetails.user')),
            ],
        ),
        migrations.CreateModel(
            name='Administration_Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administration_position', models.CharField(max_length=1000)),
                ('administration_year_from', models.CharField(max_length=1000)),
                ('administration_year_to', models.CharField(max_length=1000)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Administration_Position', to='UserDetails.user')),
            ],
        ),
    ]
