# Generated by Django 5.2.3 on 2025-08-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0002_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_details',
            name='prefix',
            field=models.CharField(default='MR', max_length=50),
            preserve_default=False,
        ),
    ]
