# Generated by Django 5.2.3 on 2025-08-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0003_staff_details_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phd',
            name='phd_scholars_produced',
        ),
        migrations.RemoveField(
            model_name='phd',
            name='phd_scholars_registered',
        ),
    ]
