# Generated by Django 4.2.25 on 2025-10-25 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0004_remove_phd_phd_scholars_produced_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_details_completed', models.BooleanField(default=False)),
                ('educational_details_completed', models.BooleanField(default=False)),
                ('research_career_completed', models.BooleanField(default=False)),
                ('career_highlights_completed', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_tracker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
