# Generated by Django 4.2.25 on 2025-11-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0006_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletracker',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
