# Generated by Django 4.2.25 on 2025-11-23 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0007_profiletracker_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiletracker',
            name='view_count',
        ),
        migrations.CreateModel(
            name='ProfileViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
